version: "3.8"

services:
  ocr-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Mapeia a porta 5000 do host para a porta 5000 do container
    volumes:
      - .:/app # Mapeia o diretório atual do host para /app no container (útil para desenvolvimento)
    environment:
      - TESSERACT_CMD=/usr/bin/tesseract # Define o caminho do Tesseract OCR
