version: "3.9"

services:
  ocr-service:
    image: registry.gitlab.com/busspass/ocr-ia-busspass:latest
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
