version: "3.8"

services:
  ocr-service:
    build: . # Usa o Dockerfile na raiz do projeto para construir a imagem
    ports:
      - "5000:80" # Mapeia a porta 5000 do host para a porta 80 do container
    volumes:
      - .:/app # Mapeia o diretório atual do host para /app no container (útil para desenvolvimento)
    environment:
      - POPPLER_PATH=/app/poppler-23.11.0/bin # Defina o caminho do poppler se necessário. **Ajuste o caminho se você tiver feito diferente**
