version: "3.8"

services:
  ocr-service:
    build: .
    container_name: ocr-service
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "8002:8002"

  nginx:
    image: nginx:alpine
    container_name: ocr-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ocr-service
